[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile --prod=false"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "node dist/main"

[variables]
NODE_ENV = "production"
